version: "3.0"
services:
    mysql:
        image: mysql:8.0
        ports:
        - 3306:3306
        volumes:
        - /var/lib/mysql
        environment:
            MYSQL_DATABASE: musicdb
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456